# Introdução à Data Science com Python - Data ICMC-USP

Esse material foi desenvolvido pelo Data, grupo de extensão de aprendizado e ciência de dados compostos por alunos do Instituto de Ciências Matemáticas e de Computação da USP.

Esse notebook é acompanhado de um curso em video, que pode ser encontrado em [aqui](https://www.youtube.com/playlist?list=PLFE-LjWAAP9SfEuLXf3qrpw4szKWjlYq9)

Para saber mais sobre as atividades do Data entre no nosso site e nos siga e nossas redes sociais:
- [Site](http://data.icmc.usp.br/)
- [Twitter](https://twitter.com/data_icmc)
- [LinkedIn](https://www.linkedin.com/school/data-icmc/)
- [Facebook](https://www.facebook.com/dataICMC/)

Aproveite o material!

## Exercícios Python

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos nas aulas de Python. Esse material foi preparado para acompanhar o que foi passado nos videos, e em breve teremos a divulgação das resuluções com um vídeo de explicação.

### Variáveis

In [7]:
# Declare uma variavel chamada a e atribua o valor 10 a ela
a = 10
a

10

In [8]:
# Imprime essa variavel que você acabou de criar
a

10

In [9]:
# Crie uma outra variavel b que recebe o valor de a so que como string
b = str(a)

b

'10'

In [11]:
# Combine sua variavel b a variavel abaixo para obter a string "Hello 10" em uma variavel d
c = "Hello "
d = c + b

In [12]:
# Imprima a variável d
d

'Hello 10'

### Strings

In [13]:
my_str = 'Insira uma frase aqui!'

In [16]:
# Substitua a exclamação da frase por uma interrogação
# (Dica: A funcão altera inplace ou retorna uma copia modificada?)

my_str.replace("!", "?")
# é retornado uma nova string, pois a string original dentro my_str não é alterado

'Insira uma frase aqui?'

In [17]:
# Crie uma lista "my_words" com cada palavra a frase
my_words = "Python é uma linguagem foda pra krai"
my_words.split()

['Python', 'é', 'uma', 'linguagem', 'foda', 'pra', 'krai']

### Listas

In [2]:
lista = [1, 23, 31, 40, 56, 16]

In [3]:
# Faça um for que imprima cada elemento da lista "lista" (Lembre-se que o for em python é um for each)
for num in lista:
    print(num)

1
23
31
40
56
16


In [4]:
# Faça um for que imprima o dobro de cada elemento da lista "lista" 
for num in lista:
    print(num * 2)

2
46
62
80
112
32


In [18]:
# Gere uma lista chamada "dobro" com o dobro de cada elemento de "lista" usando list comprehension
dobro = [num * 2 for num in lista]
dobro

[2, 46, 62, 80, 112, 32]

In [46]:
# Crie uma nova lista chamada "pares"
# Faça um for que itetere sobre a lista "lista" e para cada elemento impar coloque ele no fim da lista "pares"
# Imprima a lista "pares"
pares = [num for num in reversed(lista)]
print(pares)

[16, 56, 40, 31, 23, 1]


In [49]:
lista2 = ['oi', 2, 2.5, 'top', 'python', 45]

In [50]:
# Faça um for pela "lista2" e imprima todos os elementos que são strings (Dica: pesquise pela função type())
for palavras in lista2:
    if type(palavras) == str:
        print(palavras)

oi
top
python


#### Indexando

In [51]:
my_list = [0, 10, 20, 30, 40, 50, 60, 70]

In [52]:
# Selecione o ultimo elemento da lista
my_list[-1]

70

In [55]:
# Selecione do primeiro até o 4 elemento da lista
my_list[0:5]

[0, 10, 20, 30, 40]

In [56]:
# Selecione do segundo elemento da lista até o quinto
my_list[1:5]

[10, 20, 30, 40]

In [60]:
# Selecione do primeiro elemento da lista até o penultimo
my_list[0:-1] 

[0, 10, 20, 30, 40, 50, 60]

### Dicionários

In [62]:
lista = ['a', 'a', 'b', 'a', 'c', 'd', 'e', 'b', 'b', 'c']

In [65]:
# Crie um dicionario que contenha a contagem de cada elemento do vetor
my_dict = {}
#...
my_dict['a'] = lista.count('a')
my_dict['b'] = lista.count('b')
my_dict['c'] = lista.count('c')
my_dict['d'] = lista.count('d')
my_dict['e'] = lista.count('e')

In [66]:
print(my_dict)

{'a': 3, 'b': 3, 'c': 2, 'd': 1, 'e': 1}


### Funções

In [67]:
# Crie uma função soma_elementos() que recebe uma lista e retorna a soma de todos os seus elementos
def soma_elementos(lista):
    soma = 0
    for num in lista:
        soma += num
    return soma

In [68]:
soma_elementos([1, 2, 3, 4, 5])

15

In [69]:
soma_elementos([-1, 5, 7, -2])

9

In [81]:
# Crie uma função produto_escalar() que recebe duas listas de tamanho igual e calcula o produto escalar entre elas
# Dica: Utilize a função zip
def produto_escalar(lista1, lista2):
    result = 0
    for i in range(len(lista1)):
        result += lista1[i] * lista2[i]
    return result

# outra forma com zip, achei mais complicado
def produto_escalar2(lista1, lista2):
    
    result = [sum (lista1 * lista2 for lista1,lista2 in zip(lista1,lista2))]
    return result

In [82]:
produto_escalar2([1, 2, 3], [0, 4, 7])

[29]

In [72]:
produto_escalar([10, 20, 40, 1], [23, 4, 2, 1])

391

In [30]:
# Crie uma função par_ou_impar() que recebe um numero n é para cada numero de 1 a n imprime o numero
# seguido de par ou impar, dependendo do que ele seja. Caso o usuário não coloque nada n deve valer 20
# Exemplo: par_ou_impar(4)
#   1 Impar
#   2 Par
#   3 Impar
#   4 Par
def par_ou_impar(num = 20):
    for i in range(num):
        i += 1
        if i % 2 == 0:
            print(i, " Par")
        elif i % 2 == 1:
            print(i, " Impar")
        

In [31]:
par_ou_impar(4)

1  Impar
2  Par
3  Impar
4  Par


In [33]:
par_ou_impar()

1  Impar
2  Par
3  Impar
4  Par
5  Impar
6  Par
7  Impar
8  Par
9  Impar
10  Par
11  Impar
12  Par
13  Impar
14  Par
15  Impar
16  Par
17  Impar
18  Par
19  Impar
20  Par


In [45]:
# Crie uma função diga_indice() que recebe uma lista e imprime o indice de cada elemento e em seguida 
# o proprio elemento
# Exemplo: diga_indice(['oi', 'tudo', 'bem'])
#    0 oi
#    1 tudo
#    2 bem
# (DICA: Pesquise pela função enumerate)

def diga_indice(lista):
    for i in lista:
        print(lista.index(i), i)

In [46]:
diga_indice(['1', '2', '3'])

0 1
1 2
2 3


In [47]:
diga_indice(['a', 'b', 'c', 'd', 'e'])

0 a
1 b
2 c
3 d
4 e


## Numpy

O elemento central do numpy são os arrays, então aqui vamos treinar muitas coisas sobre eles

In [48]:
# Importando a biblioteca
import numpy as np

### Arrays

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [54]:
# Pense em qual é a shape de cada um dos arrays acima
#a = 7
#b = 2,4
#c = 3,4
# Depois de pensar imprima cada um deles para conferir sua resposta
a.shape
b.shape
c.shape

(3, 4)

In [62]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23bb
arrayOneDimension = np.random.randint(23, size=20)
arrayOneDimension

array([14,  4,  5, 22, 22,  3,  6, 18,  9, 19, 21,  2, 18,  5, 19,  0, 11,
       17,  0, 14])

In [65]:
# Crie um array de uns com shape (4, 5)
arrayUns = np.ones((4,5))
arrayUns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
# Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)
array = np.full((4,2), 77)
array

array([[77, 77],
       [77, 77],
       [77, 77],
       [77, 77]])

In [81]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]
my_sequence = np.arange(0, 110, 10)
my_sequence

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### Indexando

In [82]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[23 15 27  4 27  0 10 16 13 32  8  2 46 34 42]


In [87]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
my_array[5:12]

array([ 0, 10, 16, 13, 32,  8,  2])

In [94]:
# Selecione todos os elementos maiores que 20
my_array[my_array > 20]

array([23, 27, 27, 32, 46, 34, 42])

In [113]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [104]:
# Selecione o elemento na primeira linha da terceira coluna
my_matrix[0,2]

3

In [107]:
# Selecione o elemento na primeira linha da ultima coluna
my_matrix[0,-1]

4

In [143]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]
my_matrix[1:3, 1:3]

# o primeiro parametro são as linhas e o segundo as colunas

array([[ 6,  7],
       [10, 11]])

In [148]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]
my_matrix[0:2, 1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [158]:
# Selecione os elementos da ultima coluna inteira
my_matrix[:, 3]

array([ 4,  8, 12, 16])

In [160]:
# Selecione os elementos da 2a linha inteira
my_matrix[1]

array([5, 6, 7, 8])

### Operações

In [204]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[3 5 6 8 8]


In [169]:
# Some 10 a todos os elementos de my_array
my_array + 10

array([19, 16, 12, 13, 14])

In [192]:
# Multiplique todos os elementos de my_array por 4
outro_array = my_array * 4
print(outro_array)

[ 8  0 20 12  8]


In [194]:
# Obtenha a soma de todos os elementos de my_array
my_array.sum()

12

In [195]:
# Obtenha a média de todos os elementos de my_array
my_array.mean()

2.4

In [207]:
# Obtenha o indice do maior elemento de my_array
my_array[np.argmax(my_array)] # maior valor
my_array.argmax()


3

In [202]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[1 1 9 0 9] 

[1 3 2 9 7]


In [208]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[8 3 3 9 8] 

[[3 5 2 7 4]
 [1 0 4 1 7]
 [8 0 2 5 2]
 [0 4 1 0 8]
 [8 8 0 6 8]
 [6 9 3 2 8]
 [1 8 7 4 7]
 [3 0 5 3 9]
 [5 7 3 5 6]
 [5 8 5 7 8]]


In [209]:
# Some my_array elemento por elemento em cada linha de my_other_array
np.add(my_array, my_other_array)

array([[11,  8,  5, 16, 12],
       [ 9,  3,  7, 10, 15],
       [16,  3,  5, 14, 10],
       [ 8,  7,  4,  9, 16],
       [16, 11,  3, 15, 16],
       [14, 12,  6, 11, 16],
       [ 9, 11, 10, 13, 15],
       [11,  3,  8, 12, 17],
       [13, 10,  6, 14, 14],
       [13, 11,  8, 16, 16]])

In [212]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[5 7 6 0]
 [9 6 8 0]
 [3 2 2 4]
 [0 5 8 1]
 [5 0 6 2]] 

[[0 1 4 2 9]
 [0 5 6 3 5]
 [2 6 2 3 5]
 [5 0 0 7 9]
 [7 2 9 1 3]
 [0 2 6 8 5]
 [7 3 2 0 0]
 [1 9 4 6 2]
 [6 7 2 1 5]
 [2 6 2 5 8]]


In [219]:
# Faça a multiplicação entre my_other_array e my_array
# refrescando a memoria: para funcionar a multiplicação, n elementos das linhas tem que ser igual a n elementos da coluna da outra
np.dot(my_other_array, my_array)

array([[ 66,  24,  86,  36],
       [ 88,  57, 106,  37],
       [ 95,  69, 118,  21],
       [ 70,  70, 140,  25],
       [ 95,  84, 102,  43],
       [ 61,  64, 122,  42],
       [ 68,  71,  70,   8],
       [108,  99, 146,  26],
       [124,  93, 134,  19],
       [110,  79, 152,  29]])

In [220]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)
np.sum(my_other_array, axis=1)

array([16, 19, 18, 21, 22, 21, 12, 22, 21, 23])

In [221]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[3 1 7 7]
 [3 6 8 7]
 [0 1 6 5]
 [0 7 2 4]
 [8 0 8 0]]


In [226]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)
my_array.reshape(20)

array([3, 1, 7, 7, 3, 6, 8, 7, 0, 1, 6, 5, 0, 7, 2, 4, 8, 0, 8, 0])

In [227]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [230]:
# Gere a array anterior usando np.arange e a função reshape
arrayBolado = np.arange(0,16,1)
arrayBolado.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])